### ISSUE TITLE
Avoid converting blocks into long, single-line blocks

### ISSUE THREAD

**Issue by gschlager** [ruby-syntax-tree/syntax_tree#245]
I think stree should disregard the configured `print-width` and use multi-line blocks instead of single-line blocks when the line length exceeds ~60 chars.

Okay:
```ruby
File.open(source_file_path, "rb") do |file|
  IO.copy_stream(file, @write_only_io)
end
```

Harder to read:
```ruby
File.open(source_file_path, "rb") { |file| IO.copy_stream(file, @write_only_io) }
```

(Tested with `print-width` of 100)

**Comment by kddnewton** [comment]
So unfortunately this is pretty fundamental to the algorithm that we use for printing. We only have the one breakpoint, because it ends up being much more efficient than checking for multiples that are context-dependent. In this case I would suggest either lowering your print width to 80 (the default) or using an `# stree-ignore` comment to keep the formatting as you see fit.
